---

version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'type: dependencies'
      - 'cargo'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - 'type: dependencies'
      - 'github-actions'
