---

specfile_path: ./rust-ifcfg-devname.spec
upstream_tag_template: "v{version}"

upstream_package_name: ifcfg-devname
downstream_package_name: rust-ifcfg-devname

srpm_build_deps: []

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-stable-x86_64
      - fedora-rawhide-x86_64

  - <<: *copr
    trigger: release
