---

specfile_path: ./rust-ifcfg-devname.spec
upstream_tag_template: "v{version}"

upstream_package_name: ifcfg-devname
downstream_package_name: rust-ifcfg-devname

jobs:
  - &copr
    job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide-x86_64
      - centos-stream-9-x86_64

  - <<: *copr
    trigger: release

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - main
