[package]
name = "ifcfg-devname"

version = "0.1.3"
edition = "2021"
license = "GPL-3.0"
authors = ["Jan Macku <jamacku@redhat.com>"]
repository = "https://github.com/jamacku/ifcfg-devname"
exclude = ["./.codecov.yml", "./mergify.yml", "/target/*", "/.github/*"]

keywords = ["ifcfg", "udev"]
categories = []
description = "Udev helper utility that provides network interface naming using kernel cmdline and ifcfg configuration"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.1"

# globbing
glob = "0.3.0"

# parsing
regex = "1.5.4"
lazy_static = "1.4.0"

# logging
syslog = "^6.0.1"
log = "0.4.14"
stderrlog = "0.5.1"


# integration testing
[dev-dependencies]

# command exevution
assert_cmd = "2.0.2"
predicates = "2.1.0"

# JSON
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
