[package]
name = "ifcfg-devname"
version = "0.1.0"
authors = ["Jan Macku <jamacku@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mac_address = "1.1.1"

# globbing
glob = "0.3.0"

# parsing
regex = "1.5.4"
lazy_static = "1.4.0"

# logging
syslog = "6.0.0"
log = "0.4.14"
stderrlog = "0.5.1"


# integration testing
[dev-dependencies]

# command exevution
assert_cmd = "2.0.2"
predicates = "2.0.3"

# JSON
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.71"
