[package]
name = "rename_device"
version = "0.1.0"
authors = ["Jan Macku <jamacku@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
mac_address = "1.1.1"
