[package]
name = "ifcfg_devname"
version = "0.1.0"
authors = ["Jan Macku <jamacku@redhat.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
mac_address = "1.1.1"
glob = "0.3.0"
regex = "1.5.4"
lazy_static = "1.4.0"
