# Generated by rust2rpm 20
%bcond_without check

%global crate ifcfg-devname

Name:           rust-%{crate}
Version:        1.1.0
Release:        %autorelease
Summary:        Udev helper utility that provides network interface naming

# Upstream license specification: GPL-3.0
License:        GPL-3.0-or-later
URL:            https://crates.io/crates/ifcfg-devname
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging

%global _description %{expand:
Udev helper utility that provides network interface naming using ifcfg configuration.}

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}
License:        GPL-3.0-or-later and MIT

%description -n %{crate} %{_description}

%files       -n %{crate}
%license LICENSE
%doc README.md

%{_bindir}/ifcfg-devname
%{_udevrulesdir}/60-net.rules

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license LICENSE
%doc README.md
%{cargo_registry}/%{crate}-%{version_no_tilde}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version_no_tilde}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

install -m 0755 -d $(DESTDIR)$(libdir)/udev

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
