---

name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Upload
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
